# Generated by Django 4.2.7 on 2025-12-04 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Household', 'Household')], default='Household', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=30, unique=True)),
                ('liters_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('billing_period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('household_code', models.CharField(max_length=20, unique=True)),
                ('household_name', models.CharField(max_length=100)),
                ('head_of_household', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=16, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('cell', models.CharField(blank=True, max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('number_of_members', models.IntegerField(default=1)),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('connection_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_households', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'households',
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liters_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_date', models.DateField()),
                ('reading_month', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Billed', 'Billed')], default='Pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_usages', to='api.household')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_usage',
            },
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('tariff_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_name', models.CharField(max_length=100)),
                ('rate_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tariff_rates',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.bill')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.household'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tariffrate'),
        ),
        migrations.AddField(
            model_name='bill',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.waterusage'),
        ),
        migrations.AddIndex(
            model_name='waterusage',
            index=models.Index(fields=['reading_month'], name='water_usage_reading_3fd951_idx'),
        ),
        migrations.AddIndex(
            model_name='waterusage',
            index=models.Index(fields=['household'], name='water_usage_househo_b5791d_idx'),
        ),
        migrations.AddIndex(
            model_name='waterusage',
            index=models.Index(fields=['status'], name='water_usage_status_69d136_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waterusage',
            unique_together={('household', 'reading_month')},
        ),
        migrations.AddIndex(
            model_name='tariffrate',
            index=models.Index(fields=['is_active'], name='tariff_rate_is_acti_4e7947_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffrate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='tariff_rate_effecti_730c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill'], name='payments_bill_id_21939b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['household_code'], name='households_househo_15af39_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['national_id'], name='households_nationa_b5014b_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['status'], name='households_status_a8a8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='bills_bill_nu_ba9272_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['household'], name='bills_househo_5f0480_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='bills_status_d22f38_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['billing_period'], name='bills_billing_fb5c27_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
