# Generated by Django 4.2.7 on 2025-12-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Bill Generated', 'Bill Generated'), ('Payment Confirmation', 'Payment Confirmation'), ('General', 'General')], default='General', max_length=30)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms_notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
